//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CubePdf.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CubePdf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   CubePDF について に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CubePDF エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は既に存在します。{1}しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルが指定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNotSpecified {
            get {
                return ResourceManager.GetString("FileNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Header {
            get {
                object obj = ResourceManager.GetObject("Header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   CubePDF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PS ファイル (*.ps)|*.ps;*.PS|EPS ファイル (*.eps)|*.eps;*.EPS|PDF ファイル (*.pdf)|*.pdf;*.PDF|すべてのファイル (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputPathFilter {
            get {
                return ResourceManager.GetString("InputPathFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   / * : ? &quot; &lt; &gt; | に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidFilename {
            get {
                return ResourceManager.GetString("InvalidFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル名には次の文字は使えません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidFilenameTitle {
            get {
                return ResourceManager.GetString("InvalidFilenameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   先頭に結合 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MergeHead {
            get {
                return ResourceManager.GetString("MergeHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   末尾に結合 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MergeTail {
            get {
                return ResourceManager.GetString("MergeTail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   何もしない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PDF ファイル (*.pdf)|*.pdf;*.PDF|PS ファイル (*.ps)|*.ps;*.PS|EPS ファイル (*.eps)|*.eps;*.EPS|PNG ファイル (*.png)|*.png;*.PNG|JPEG ファイル (*.jpg;*.jpeg)|*.jpg;*.JPG;*.jpeg;*.JPEG|BMP ファイル (*.bmp)|*.bmp;*.BMP|TIFF ファイル (*.tiff;*.tif)|*.tiff;*.TIFF;*.tif;*.TIF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutputPathFilter {
            get {
                return ResourceManager.GetString("OutputPathFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書き に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Overwrite {
            get {
                return ResourceManager.GetString("Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力されたパスワードが一致しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PasswordUnmatched {
            get {
                return ResourceManager.GetString("PasswordUnmatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CubePDF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リネーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたパスが長すぎます。
        ///パス全体は260文字未満、ディレクトリ名は248文字未満で指定して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TooLongFilenam {
            get {
                return ResourceManager.GetString("TooLongFilenam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集パスワードと閲覧パスワードを共用すると、各種操作の制限が正常に機能しない可能性があります。
        ///閲覧パスワードに編集パスワードとは異なるものを設定するか、または、全ての操作を許可して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserPasswordRequired {
            get {
                return ResourceManager.GetString("UserPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザープログラム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserProgram {
            get {
                return ResourceManager.GetString("UserProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行可能プログラム (*.exe, *.bat)|*.exe;*.EXE;*.bat;*.BAT|すべてのファイル (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserProgramFilter {
            get {
                return ResourceManager.GetString("UserProgramFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CubePDF 確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
    }
}
