//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CubePDF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TempInput.ps")]
        public string INPUT_FILENAME {
            get {
                return ((string)(this["INPUT_FILENAME"]));
            }
            set {
                this["INPUT_FILENAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("REDMON_FILENAME")]
        public string REDMON_FILENAME {
            get {
                return ((string)(this["REDMON_FILENAME"]));
            }
            set {
                this["REDMON_FILENAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cube.pdf")]
        public string DEFAULT_OUT_FILENAME {
            get {
                return ((string)(this["DEFAULT_OUT_FILENAME"]));
            }
            set {
                this["DEFAULT_OUT_FILENAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PDF ファイル(*.pdf)|*.pdf|すべてのファイル(*.*)|*.*")]
        public string DIALOG_PDF_FILTER {
            get {
                return ((string)(this["DIALOG_PDF_FILTER"]));
            }
            set {
                this["DIALOG_PDF_FILTER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PNG ファイル(*.png)|*.png|すべてのファイル(*.*)|*.*")]
        public string DIALOG_PNG_FILTER {
            get {
                return ((string)(this["DIALOG_PNG_FILTER"]));
            }
            set {
                this["DIALOG_PNG_FILTER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JPEG ファイル(*.jpg;*.jpeg)|*.jpg;*.jpeg|すべてのファイル(*.*)|*.*")]
        public string DIALOG_JPEG_FILTER {
            get {
                return ((string)(this["DIALOG_JPEG_FILTER"]));
            }
            set {
                this["DIALOG_JPEG_FILTER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BMP ファイル(*.bmp)|*.bmp|すべてのファイル(*.*)|*.*")]
        public string DIALOG_BMP_FILTER {
            get {
                return ((string)(this["DIALOG_BMP_FILTER"]));
            }
            set {
                this["DIALOG_BMP_FILTER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TIFF ファイル(*.tiff;*.tif)|*.tiff;*.tif|すべてのファイル(*.*)|*.*")]
        public string DIALOG_TIFF_FILTER {
            get {
                return ((string)(this["DIALOG_TIFF_FILTER"]));
            }
            set {
                this["DIALOG_TIFF_FILTER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("名前を付けて保存")]
        public string DIALOG_TITLE {
            get {
                return ((string)(this["DIALOG_TITLE"]));
            }
            set {
                this["DIALOG_TITLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PDF")]
        public string FILETYPE_PDF {
            get {
                return ((string)(this["FILETYPE_PDF"]));
            }
            set {
                this["FILETYPE_PDF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PNG")]
        public string FILETYPE_PNG {
            get {
                return ((string)(this["FILETYPE_PNG"]));
            }
            set {
                this["FILETYPE_PNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JPEG")]
        public string FILETYPE_JPEG {
            get {
                return ((string)(this["FILETYPE_JPEG"]));
            }
            set {
                this["FILETYPE_JPEG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BMP")]
        public string FILETYPE_BMP {
            get {
                return ((string)(this["FILETYPE_BMP"]));
            }
            set {
                this["FILETYPE_BMP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TIFF")]
        public string FILETYPE_TIFF {
            get {
                return ((string)(this["FILETYPE_TIFF"]));
            }
            set {
                this["FILETYPE_TIFF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public string VERSION_1_2 {
            get {
                return ((string)(this["VERSION_1_2"]));
            }
            set {
                this["VERSION_1_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.3")]
        public string VERSION_1_3 {
            get {
                return ((string)(this["VERSION_1_3"]));
            }
            set {
                this["VERSION_1_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.4")]
        public string VERSION_1_4 {
            get {
                return ((string)(this["VERSION_1_4"]));
            }
            set {
                this["VERSION_1_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public string VERSION_1_5 {
            get {
                return ((string)(this["VERSION_1_5"]));
            }
            set {
                this["VERSION_1_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.6")]
        public string VERSION_1_6 {
            get {
                return ((string)(this["VERSION_1_6"]));
            }
            set {
                this["VERSION_1_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.7")]
        public string VERSION_1_7 {
            get {
                return ((string)(this["VERSION_1_7"]));
            }
            set {
                this["VERSION_1_7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("開く")]
        public string POSTPROC_OPEN {
            get {
                return ((string)(this["POSTPROC_OPEN"]));
            }
            set {
                this["POSTPROC_OPEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("何もしない")]
        public string POSTPROC_NONE {
            get {
                return ((string)(this["POSTPROC_NONE"]));
            }
            set {
                this["POSTPROC_NONE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("72")]
        public string RESOLUTION_72 {
            get {
                return ((string)(this["RESOLUTION_72"]));
            }
            set {
                this["RESOLUTION_72"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public string RESOLUTION_150 {
            get {
                return ((string)(this["RESOLUTION_150"]));
            }
            set {
                this["RESOLUTION_150"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public string RESOLUTION_300 {
            get {
                return ((string)(this["RESOLUTION_300"]));
            }
            set {
                this["RESOLUTION_300"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("450")]
        public string RESOLUTION_450 {
            get {
                return ((string)(this["RESOLUTION_450"]));
            }
            set {
                this["RESOLUTION_450"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public string RESOLUTION_600 {
            get {
                return ((string)(this["RESOLUTION_600"]));
            }
            set {
                this["RESOLUTION_600"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("なし")]
        public string DOWNSAMPLE_NONE {
            get {
                return ((string)(this["DOWNSAMPLE_NONE"]));
            }
            set {
                this["DOWNSAMPLE_NONE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("平均化")]
        public string DOWNSAMPLE_AVERAGE {
            get {
                return ((string)(this["DOWNSAMPLE_AVERAGE"]));
            }
            set {
                this["DOWNSAMPLE_AVERAGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("バイキュービック")]
        public string DOWNSAMPLE_BICUBIC {
            get {
                return ((string)(this["DOWNSAMPLE_BICUBIC"]));
            }
            set {
                this["DOWNSAMPLE_BICUBIC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("サブサンプル")]
        public string DOWNSAMPLE_SUBSAMPLE {
            get {
                return ((string)(this["DOWNSAMPLE_SUBSAMPLE"]));
            }
            set {
                this["DOWNSAMPLE_SUBSAMPLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("エラー")]
        public string ERROR_TITLE {
            get {
                return ((string)(this["ERROR_TITLE"]));
            }
            set {
                this["ERROR_TITLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("入力ファイルが見つかりませんでした。仮想プリンタ経由の場合は、印刷ジョブを正常に完了できなかった可能性があります。仮想プリンタの設定を確認して下さい。")]
        public string ERROR_INPUTFILE_NOT_EXIST {
            get {
                return ((string)(this["ERROR_INPUTFILE_NOT_EXIST"]));
            }
            set {
                this["ERROR_INPUTFILE_NOT_EXIST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ファイルの変換に失敗しました。")]
        public string ERROR_CONVERT {
            get {
                return ((string)(this["ERROR_CONVERT"]));
            }
            set {
                this["ERROR_CONVERT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("入力されたパスワードが一致しません。")]
        public string ERROR_PASSWORD {
            get {
                return ((string)(this["ERROR_PASSWORD"]));
            }
            set {
                this["ERROR_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("不正なページ範囲が指定されました。")]
        public string ERROR_PAGES {
            get {
                return ((string)(this["ERROR_PAGES"]));
            }
            set {
                this["ERROR_PAGES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Web表示用の最適化に失敗しました。通常のPDFファイルを出力します。")]
        public string ERROR_WEBOPTIMIZE {
            get {
                return ((string)(this["ERROR_WEBOPTIMIZE"]));
            }
            set {
                this["ERROR_WEBOPTIMIZE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PS ファイル(*.ps)|*.ps|EPS ファイル(*.eps)|*.eps|PDF ファイル(*.pdf)|*.pdf")]
        public string DIALOG_INPUT_FILTER {
            get {
                return ((string)(this["DIALOG_INPUT_FILTER"]));
            }
            set {
                this["DIALOG_INPUT_FILTER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("REDMON_USER")]
        public string REDMON_USER {
            get {
                return ((string)(this["REDMON_USER"]));
            }
            set {
                this["REDMON_USER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PS")]
        public string FILETYPE_PS {
            get {
                return ((string)(this["FILETYPE_PS"]));
            }
            set {
                this["FILETYPE_PS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EPS")]
        public string FILETYPE_EPS {
            get {
                return ((string)(this["FILETYPE_EPS"]));
            }
            set {
                this["FILETYPE_EPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SVG")]
        public string FILETYPE_SVG {
            get {
                return ((string)(this["FILETYPE_SVG"]));
            }
            set {
                this["FILETYPE_SVG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PS ファイル(*.ps)|*.ps|すべてのファイル(*.*)|*.*")]
        public string DIALOG_PS_FILTER {
            get {
                return ((string)(this["DIALOG_PS_FILTER"]));
            }
            set {
                this["DIALOG_PS_FILTER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EPS ファイル(*.eps)|*.eps|すべてのファイル(*.*)|*.*")]
        public string DIALOG_EPS_FILTER {
            get {
                return ((string)(this["DIALOG_EPS_FILTER"]));
            }
            set {
                this["DIALOG_EPS_FILTER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SVG ファイル(*.svg)|*.svg|すべてのファイル(*.*)|*.*")]
        public string DIALOG_SVG_FILTER {
            get {
                return ((string)(this["DIALOG_SVG_FILTER"]));
            }
            set {
                this["DIALOG_SVG_FILTER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".pdf")]
        public string FILEEXTENSION_PDF {
            get {
                return ((string)(this["FILEEXTENSION_PDF"]));
            }
            set {
                this["FILEEXTENSION_PDF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".ps")]
        public string FILEEXTENSION_PS {
            get {
                return ((string)(this["FILEEXTENSION_PS"]));
            }
            set {
                this["FILEEXTENSION_PS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".eps")]
        public string FILEEXTENSION_EPS {
            get {
                return ((string)(this["FILEEXTENSION_EPS"]));
            }
            set {
                this["FILEEXTENSION_EPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".svg")]
        public string FILEEXTENSION_SVG {
            get {
                return ((string)(this["FILEEXTENSION_SVG"]));
            }
            set {
                this["FILEEXTENSION_SVG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".png")]
        public string FILEEXTENSION_PNG {
            get {
                return ((string)(this["FILEEXTENSION_PNG"]));
            }
            set {
                this["FILEEXTENSION_PNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".jpg")]
        public string FILEEXTENSION_JPEG {
            get {
                return ((string)(this["FILEEXTENSION_JPEG"]));
            }
            set {
                this["FILEEXTENSION_JPEG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".bmp")]
        public string FILEEXTENSION_BMP {
            get {
                return ((string)(this["FILEEXTENSION_BMP"]));
            }
            set {
                this["FILEEXTENSION_BMP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".tiff")]
        public string FILEEXTENSION_TIFF {
            get {
                return ((string)(this["FILEEXTENSION_TIFF"]));
            }
            set {
                this["FILEEXTENSION_TIFF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("使用可能な期限を過ぎました。引き続き使用する場合は CubePDF のアップデートを行って下さい。今すぐ CubePDF の Web ページへ移動しますか？")]
        public string ERROR_CERTIFY {
            get {
                return ((string)(this["ERROR_CERTIFY"]));
            }
            set {
                this["ERROR_CERTIFY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("は既に存在します。")]
        public string WARNING_FILE_EXIST {
            get {
                return ((string)(this["WARNING_FILE_EXIST"]));
            }
            set {
                this["WARNING_FILE_EXIST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("保存の確認")]
        public string WARNING_SAVE_TITLE {
            get {
                return ((string)(this["WARNING_SAVE_TITLE"]));
            }
            set {
                this["WARNING_SAVE_TITLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("上書き")]
        public string EXISTED_FILE_OVERWRITE {
            get {
                return ((string)(this["EXISTED_FILE_OVERWRITE"]));
            }
            set {
                this["EXISTED_FILE_OVERWRITE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("末尾に結合")]
        public string EXISTED_FILE_MERGE_TAIL {
            get {
                return ((string)(this["EXISTED_FILE_MERGE_TAIL"]));
            }
            set {
                this["EXISTED_FILE_MERGE_TAIL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("先頭に結合")]
        public string EXISTED_FILE_MERGE_HEAD {
            get {
                return ((string)(this["EXISTED_FILE_MERGE_HEAD"]));
            }
            set {
                this["EXISTED_FILE_MERGE_HEAD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("しますか？")]
        public string WARNING_DO {
            get {
                return ((string)(this["WARNING_DO"]));
            }
            set {
                this["WARNING_DO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ユーザープログラム")]
        public string POSTPROC_OTHER {
            get {
                return ((string)(this["POSTPROC_OTHER"]));
            }
            set {
                this["POSTPROC_OTHER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Windows バッチ ファイル(*.bat)|*.bat|アプリケーション(*.exe)|*.exe|すべてのファイル(*.*)|*.*")]
        public string DIALOG_EXEC_FILTER {
            get {
                return ((string)(this["DIALOG_EXEC_FILTER"]));
            }
            set {
                this["DIALOG_EXEC_FILTER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("外部プログラムを選択")]
        public string DIALOG_TITLE_EXEC {
            get {
                return ((string)(this["DIALOG_TITLE_EXEC"]));
            }
            set {
                this["DIALOG_TITLE_EXEC"] = value;
            }
        }
    }
}
